application: chirpradio
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /api/.*
  script: api/handler.py

# Support for remote datastore access.  For more information, please see
# http://code.google.com/appengine/articles/remote_api.html
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# Serve static media with a 2 hour TTL.  Note that everything under
# media is world-readable!
- url: /media
  static_dir: media
  expiration: 2h

# restrict public access to task queue URL handlers
- url: /playlists/task/.*
  script: main.py
  login: admin

# For everything else, we always want to use HTTPS.
- url: /.*
  secure: always
  script: main.py


inbound_services:
- warmup


builtins:
- datastore_admin: on


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- testlib/.*
